### ISSUE TITLE
Error opening all downloaded files

### ISSUE THREAD

**Issue by cphill02** [tarunbatta/excelexportjs#17]
examplejson.html works but thows an error when I try to open the downloaded file:
"The file you are trying to open, 'ihNTD5Wv.xls.xls', is in a different format than specified by the file extension. Verify that the file is not corrupted and is from a trusted source before opening the file. Do you want to open the file now?

Using jQuery 1.11.0
Using Windows 7 w/ MS Excel 2010:
Confirmed issue on browsers Firefox 28 & Chrome 34

**Comment by cosmocracy** [comment]
Verified.  Looks like this is a "feature" added to Office 2007 and beyond:
https://support.microsoft.com/en-us/kb/948615

**Comment by tarunbatta** [comment]
I have rolled out excelexportjs 4.0.0 version. Please use the same.
