### ISSUE TITLE
Plugin not support multiple worksheet

### ISSUE THREAD

**Issue by govindbhatu** [tarunbatta/ExcelExportJs#37]
Hello,

This plugin does not support multiple worksheets. I does have a requirement in which I have 3 table and needs to export them into three different worksheets within single excel file.

Please let me know if you are able to do it or not.

Thanks in advance.

**Comment by tarunbatta** [comment]
This feature is currently supported with server side implementation, http://techbytarun.com/export-excel-sheet-using-c-sharp/
