### ISSUE TITLE
doublerowed xls-file

### ISSUE THREAD

**Issue by Silverbullet78** [tarunbatta/excelexportjs#39]
Hi, tarunbatta! 
Generating excel-file from html-table  I get excel-table with rows like if I used style "rowspan='2'" but I do not use it. How to fix this? Thanks beforehand!

**Comment by tarunbatta** [comment]
can you please share a plunker for the same?

**Comment by tarunbatta** [comment]
I have rolled out excelexportjs 4.0.0 version, which takes care of this feature. Please use the same.
