### ISSUE TITLE
Large data issue

### ISSUE THREAD

**Issue by yyogesh** [tarunbatta/excelexportjs#40]
Large data(50000 row) issue on chrome. Working fine on firefox and ie.

**Comment by pawanupr16** [comment]
I am Facing same issue. not able to excel export in Pivot table.  there is any API for this ??

**Comment by muhammednigil** [comment]
In function Export

change the below code to 

var uri = "data:application/vnd.ms-excel;base64,";
 var ctx = { worksheet: $settings.worksheetName, table: htmltable };
return (uri + base64(format(excelFile, ctx)));


**new code** 

xData = new Blob([htmltable], { type: 'text/csv' });
var xUrl = URL.createObjectURL(xData);
return xUrl;

            //

**Comment by tarunbatta** [comment]
I have rolled out excelexportjs 4.0.0 version, which takes care of this feature. Please use the same.
