### ISSUE TITLE
Added ishidden property to column, for datatype 'table'

### ISSUE THREAD

**Issue by MarkSamp** [tarunbatta/excelexportjs#41]
I don´t know if this is the right place, but i want to share a modification that i´ve made to the plugin.

Sometimes, we need to "hide" some columns, from a html table, in exported excel file, ex. A column action buttons from a datagrid. So i´ve made this modification in line 94:

`
function ConvertFromTable() {
			var tbl = $('#' + $settings.containerid).clone();
			$(tbl).find("td").each(function(){
				if($(this).attr("ishidden") == "true" ){
					$(this).remove();  
				}
			});
            var result = $('<div>').append(tbl).html();
            return result;
        }
`

and add this: ' ishidden="true"' on the column(s) tag that you need to hide.

This will loop all the 'td' tags, and remove those with ishidden="true" property.

Any improvements are aprecciated!

**Comment by tarunbatta** [comment]
I have rolled out excelexportjs 4.0.0 version, which takes care of this feature. Please use the same.
