### ISSUE TITLE
Left zeroes removing with angularJs

### ISSUE THREAD

**Issue by Shadowstep** [tarunbatta/excelexportjs#42]
Hello

I`ve been trying to use your tool to map an excel file using AngularJs 

the problem is the same as i saw in one of the closed issues: i have a field with 004 .. (i`m sending 004 from back-end) and the excel displays 4  if the column is formated as stardard. somehow i have to make the whole column format as text.

here is the code from the report.controller.js:

    $('#releaseAddBtn').on('click', function () {
        $('#dvjson').excelexportjs({
                    containerid: 'dvjson',
                    datatype: 'json',
                    dataset: vm.data,
                    dataformat: 'string',
                    columns: vm.getColumns() 
                });
    });    
    
    vm.getColumns = function(){
        var completeColumns = [];
        var values = vm.allReporttyp[vm.selectedReport].fields ;
        var headers = vm.allReporttyp[vm.selectedReport].headers;
        
        for(var q = 0; q < headers.length; q++) {
            var obj = {};
            obj['headertext'] = headers[q];
            obj['datatype'] = 'string';
            obj['datafield'] = values[q];
            completeColumns.push(obj);
        }

        return completeColumns;
    };
      
}

i saw the C# code but unfortunately id does not help me, as my app is made with js and angularjs. Maybe you could give me a hand.
Thank you

**Comment by tarunbatta** [comment]
I have rolled out excelexportjs 4.0.0 version, which takes care of this feature. Please use the same.
