### ISSUE TITLE
Download HTML Content.

### ISSUE THREAD

**Issue by prvinuch** [tarunbatta/excelexportjs#43]
Hi Tarun,
I'm trying to export json data in excel sheet, one of my column contains html code for each row, when I download this data then excel does not show me html code but instead it shows formatted html data and data get splitted in multiple rows.

Can you pleaese let me know is there any way we can download the html code which can be confined to single cell instead of many.

Regards,
Praveen Agarwal

**Comment by tarunbatta** [comment]
can u please share a JsFiddle for this use case.

**Comment by tarunbatta** [comment]
I have rolled out excelexportjs 4.0.1 version. Please use the same.
