### ISSUE TITLE
Change downloaded filename ?

### ISSUE THREAD

**Issue by vv7v7** [tarunbatta/ExcelExportJs#44]
Dear Developers,
Is there any chance to change download file name to file.xml ?

Best regards,
V7

**Comment by muhammednigil** [comment]
$(this).attr('download', 'file.xml').attr('href', uri).attr('target', '_blank');

**Comment by vv7v7** [comment]
Dear muhammednigil,

Thank you very much really. I'll try.

Best regards,
vv7v7

**Comment by iByteDev** [comment]
what comes to be "this"?

**Comment by vv7v7** [comment]
@iByteDev an element of link/button etc. like **<a>**

**Comment by iByteDev** [comment]
Hi @vv7v7 
I tried this but I have not had good results
`function downloadToExcel(jsonData) {
    var uri = $("#dvjson").excelexportjs({
        containerid: "dvjson"
        , datatype: 'json'
        , dataset: jsonData
        , columns: getColumns(jsonData)
        , returnUri: false
    });
    let buttonDownload = `btnExport_${_id}`;
    $('#myButton').attr('download', 'file.xls').attr('href', uri).attr('target', '_blank');
}`

**Comment by vv7v7** [comment]
@iByteDev Check in example below: https://github.com/tarunbatta/excelexportjs
It shows the same, but separately.

**Comment by iByteDev** [comment]
@vv7v7 
I'm going to check it out. thanks
