### ISSUE TITLE
Need Urgent Help in some issue

### ISSUE THREAD

**Issue by kappu1996** [tarunbatta/excelexportjs#45]
Hi Tarun,
I appreciate what you did and i tried your excel export it's working fine but need your help in some issue..
1.) In Excel default vertical alignment set to bottom but i need center so can you please tell me how to do this ?
2.) Between some rows excel is taking some line gap and that is not in HTML table so how can i get as it is table from HTML.

I look forward to hear from you very soon.

Thanks,
Kapil (Kapil1996goyal@gmail.com)

**Comment by tarunbatta** [comment]
I have rolled out excelexportjs 4.0.0 version, which takes care of this feature. Please use the same.
