### ISSUE TITLE
Not Working in Internet Explorer and Microsoft Edge Browser

### ISSUE THREAD

**Issue by kappu1996** [tarunbatta/excelexportjs#47]
Hi All,

Can anyone please suggest "How to make this "Excel Export" workable in IE and Microsoft Edge Browser ? Because i tried multiple way even by allowing JS and JQuery in Browser but still not working.

Regards,
Kapil

**Comment by tarunbatta** [comment]
I have rolled out excelexportjs 4.0.0 version, which takes care of this feature. Please use the same.
